SOURCES = game.ml
PACKS = universe
#PACKS = lablgtk2.gnomecanvas unix
#INCDIRS = ../../library
#LIBS = socket color image world
RESULT = game
OCAMLMAKEFILE = ../../OCamlMakefile
include $(OCAMLMAKEFILE)
